docs/CONTRIBUTING.md
docs/SECURITY.md

* Add a `CONTRIBUTING.md` file, describing how contributors can build, test, and contribute back to the project.
* Add a `SECURITY.md` file, describing how contributors can file security concerns to NI.
These project files are good ideas to have, and also required to comply with NI's policy on GH project maintainership.
AB#2791142
None; documentation changes.

.github: add CONTRIBUTING file and PR template

---

src/configure-nilrt-snac
src/nilrt-snac

Add a blacklist file in /etc/modprobe.d that will prevent `cfg80211` and `mac80211` kernel modules from loading. This is to prevent any WiFi networks from working
US#2816965 - [SNAC Auth] Remove wireless driver from NILRT via SNAC configuration tool
Manually add a file with the same contents and verified the wlan0 interface was gone after rebooting. Removing the file allowed wlan0 to reappear

Add step to disable WiFi

---

.gitignore
Makefile
src/configure-nilrt-snac
src/nilrt-snac-conflicts/Makefile
src/nilrt-snac-conflicts/control

Some parts of the SNAC configuration prohibit the installation of certain packages like ni-auth or xserver. But these packages might accidentally get reinstalled as dependencies of other package installations.
As a protection against that happening, construct a meta-package called nilrt-snac-conflicts, that contains no data, but conflicts with prohibited packages. Install it to the system after uninstalling the bad packages, to keep them from getting reinstalled.
[AB#2791297](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2791297)
The [nilrt-snac configure script](https://github.com/amstewart/nilrt-snac/blob/master/src/configure-nilrt-snac) de-installs ni-auth as one of its first steps, in order to keep the niauth database from conflicting with subsequent …

Install a nilrt-snac-conflicts meta-package

---

.github/workflows/check_signoffs.sh
.github/workflows/pr-commit-check.yml

By repo policy, all commits should have a signed-off-by trailer. Add a Github PR to check for this policy.
This repo's policy requires commits to be signed. This pipeline will help devs remember to add their signoffs.
Tested on my repo [here](https://github.com/amstewart/nilrt-snac/pull/1).
Failed test output looks like [this](https://github.com/amstewart/nilrt-snac/actions/runs/10410594541/job/28832767711?pr=1).
```
Checking commit 18de7b3bb86cea0dd0bb8c37df5b7c7b21cc2cd1... OK
Checking commit 905268475647eb897eb9cca9ccb9a8119f2ae64b... ERROR
ERROR: No signed-off-by in 905268475647eb897eb9cca9ccb9a8119f2ae64b .github: add script
Checking commit 1519c180bf76894c0c2b67d5eea92d49d5d0161f... ERROR
ERROR: No signed-off-by in 1519c180bf76894c0c2b67d5eea92d49d5d0161f squashme
Checking commit …
```

.github: add PR workflow to check signoffs

---

.github/CODEOWNERS

CODEOWNERS: add ahearn as maintainer
Alex Hearn has agreed to co-maintain this project. Add him as a
secondary maintainer for PRs.
CODEOWNERS: adjust project file permissions
Project-level files like the LICENSE and github workflows do not need to
be reviewed by all members of the R&D Security team; just the
maintainers. Add explicit rules for those files that exclude the full
team.
None; testing in github.

CODEOWNERS: add ahearn as maintainer and adjust project files

---

.github/workflows/check_signoffs.sh

Update check_signoffs.sh to check author instead of committer
[CONTRIBUTING.md#upstreaming-changes](https://github.com/tkrebes/nilrt-snac/blob/check-author-signoff/docs/CONTRIBUTING.md#upstreaming-changes) requires all authors to provide sign-off for a commit.
None

Update check_signoffs.sh to check author instead of committer

---

docs/CHANGELOG.md
src/configure-nilrt-snac

Ignore failure of the `rmmod cfg80211 mac80211` command in `disable_wifi`.
The `rmmod cfg80211 mac80211` is expected to usually fail. We want the script to complete regardless the outcome.
Successfully run `nilrt-snac configure` on a NILRT VM after modifying `configure-nilrt-snac`.

Ignore failure of rmmod cfg80211 mac80211 command

---

docs/CHANGELOG.md
src/configure-nilrt-snac

* Add setting to pam_unix.so to remember 5 passwords
* Add pam_pwquality.so to enforce password complexity
* Uses installed pwquality.conf for settings
* Add statement in "Added" section of README.md
[AB#2817094](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2817094)
* Using ipk from ni/meta-nilrt#717, verified settings were enforced with `pwscore`

configure-nilrt-snac: Add password quality enforcement

---

src/configure-nilrt-snac

add steps to configure-nilrt-snac that will install the faillock PAM plugin
pam-plugin-faillock will lock accounts after several failed attempts at authentication within a set time period.
I ran the script.
relevant output from configure-nilrt-snac:
```text
INFO: Configuring faillock...
DEBUG: Installing pam-plugin-faillock...
Downloading http://download.ni.com/ni-linux-rt/feeds/2024Q3/x64/main/core2-64/pam-plugin-faillock_1.5.2-r0.90_core2-64.ipk.
Installing pam-plugin-faillock (1.5.2) on root
Configuring pam-plugin-faillock.
```
I tested that accounts are locked after 3 failed tries by adding a user and then attempting to log in with an incorrect password 4 times.

configure faillock

---

Makefile

The Makefile 'all' target attempts to depend upon the non-existent 'nilrt-snac-conflicts' PHONY target, causing a Make failure.
Instead, have 'all' depend upon the real IPK target from nilrt-snac-conflicts, and make install depend on 'all' to inherit the same dependencies.
```bash
$ make
make: *** No rule to make target 'nilrt-snac-conflicts', needed by 'all'.  Stop.
```
Breaks local installation on NILRT and the compile stage of an OE recipe build for this project.

Makefile: fix build issue with 'all' target

---

docs/CHANGELOG.md
nilrt_snac/_configs/__init__.py
nilrt_snac/_configs/_tmux_config.py

* Add tmux configuration when snac mode is enabled
* Set lock time to 15 minutes of inactivity
* Switch shell to tmux on login so inactivity lock can be used
[AB#2816950](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2816950)
* Verified `configure` and `verify` do not crash
* Verified after running `configure` and logging out and back in tmux is the shell

Add tmux configuration

---

nilrt_snac/_pre_reqs.py

Several of the _pre_reqs system checks attempt to throw SNACErrors coded as EX_BAD_ENVIRONMENT, if they fail. But 'ENVIRONMENT' is misspelled, and so these throw AttributeErrors.
Fixup the spelling.
None; trivial.

nilrt_snac: fix misspelled enum

---

.github/workflows/pr-test.yml

Add a PR testing workflow where we can start to add autotests.
At the moment, it just checks that the Makefile workflows function, but it could be expanded to include unit tests and (if we get a NILRT runner) integration tests.

.github: add PR test

---

nilrt_snac/_configs/_pwquality_config.py

* Install `libpwquality` as part of configuring pwquality
* We rely on default settings
Needed to correctly enforce password quality
* When not installed, changing a password fails since the PAM module can not be loaded
* When installed, changing a password enforces the given requirements

Install libpwquality when configuring pwquality

---

nilrt_snac/_configs/_niauth_config.py
src/nilrt-snac-conflicts/control

remove the `niacctbase-sudo` package when configuring a SNAC target
The `niacctbase-sudo` package installs a sudo configuration file that gives special privileges to any account named `admin`.
None.

nilrt-snac: remove niacctbase-sudo package

---

nilrt_snac/_configs/_tmux_config.py

Fix file perpissions of tmux config files for non-root users
Non-root users are not using tmux properly after `nilrt-snac configure`. 
After change, non-root (both in and not in sudoers) now properly use tmux when logging int.

Set correct permissions on tmux config files

---

nilrt_snac/_configs/__init__.py
nilrt_snac/_configs/_firewall_config.py

Install firewalld and set up a default configuration which allows incoming ssh and wireguard and precious little else. Outgoing traffic permits http, https, wireguard, DHCP. wireguard interface is in "work" zone, everything else is in "public".
Manually verified that both incoming and outgoing rules are being applied. Autotesting is currently TBD.
`nilrt-snac verify`, before configure:
```
Verifying firewall configuration...
(   57) ERROR nilrt_snac.verify: MISSING: running firewalld
(   57) ERROR nilrt_snac.verify: MISSING: firewall-cmd
(   57) ERROR nilrt_snac._check_target: ERROR: policy work-in target: expected REJECT, observed /bin/sh: line 1: firewall-cmd: command not found
(   58) ERROR nilrt_snac._check_target: ERROR: policy work-out target: expected REJECT, observed /bin/sh: line …
```

_firewall_config: add

---

nilrt_snac/_configs/_pwquality_config.py

move the pam_pwquality check to higher in the PAM stack
Prior to this change, we're putting the pam_pwquality check at the bottom of `common-password`. Due to the way that PAM configuration stacking works, this means that when you try to change a password, say using `chpasswd`, to a weak password, the following happens:
- `chpasswd` returns an error code indicating failure
- `chpasswd` emits a message to stderr about which requirement failed to be met
- the password gets changed to the weak password
The first two are desirable, while the third is not. This PR removes this undesirable side effect when the user provides a weak password.
I ran `nilrt-snac configure`, then attempted to change a user's password to a weak password with `chpasswd`, then validated that the user's password did not …

nilrt-snac configure: avoid side effects when setting a weak password

---

nilrt_snac/_configs/_firewall_config.py
tests/system/remote-test-firewall.sh

The number of test cases has been quickly becoming unmanageable so I went to the woodshed for a bit and banged together a test script. I used that to make several improvements to `_firewall_config.py`.
The config changes now definitely make the firewall do what it's supposed to do at the moment, as is confirmed by the script.
Sorry, output is still a bit shaggy, I'm expecting that to get rewritten as a part of ATS integration anyway.
```
$ tests/integration/remote-test-firewall.sh macvlan1 10.1.133.47 eth1
===
=== Reading local secondary IP addresses
===
No local secondary IPv6 address found; substituting link-local address.
local ipv4: 192.168.54.1
local ipv6: fe80::4ca0:e9ff:fe06:7409%macvlan1 fe80::4ca0:e9ff:fe06:7409%eth1
===
=== Testing remote primary address connectivity
===
= TEST: …
```

Firewall: more config cleanup; manual test

---

nilrt_snac/_configs/_firewall_config.py

I had changed work-in's and public-in's targets to CONTINUE shortly before posting the PRs, but forgot to update verify() accordingly, so `nilrt-snac verify` started failing. Woops.
Verify works.

_FirewallConfig.verify: fix input policy checks

---

tests/integration/test_cli.py

The integration tests module isn't really installed like a fully-resolvable module. So we cannot use absolute module paths to import fixtures. Rather, use relative imports.
The `test_cli` integration test module fails to import fixtures when called from the ptest-runner in NILRT 10. This is because the module tries to import using `tests.integration.fixtures`, but the `tests/` directory has no `__init__.py` to make it appear like a module. Though adding a `tests/__init__.py` file also fixes this error, it isn't really *correct*, because `tests/` is really a directory of independent source components, rather than a module.
I think the reason this works in NILRT 11 is because of subtle changes in its version of `pytest`, but I'm not 100% sure. …

test_cli: use relative imports for fixtures

---

nilrt_snac/_configs/_pwquality_config.py

The `remember` option of pam_unix requires the existence of an opasswd file to store the previous passwords.
Create the file, `/etc/security/opasswd`.
Without this change, users (other than root) cannot change their password.
I ran `nilrt-snac configure` and then was able to log in as a different user and change the user's password.

nilrt-snac configure: create required file, opasswd

---

Makefile
README.md
nilrt_snac/_configs/_wireguard_config.py
src/nilrt-snac

* Change the `_wireguard_config` module to install `wireguard-tools` from a native NILRT IPK, rather than from the debian package repos.
* Fix a bug in the `nilrt-snac` wrapper script that caused local paths to pollute module execution and mess with other search paths.
[AB#2769306](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2769306)
The path fix is incidental.

Install wireguard-tools from feeds. Fix pythonpath bug.

---

nilrt_snac/_configs/__init__.py
nilrt_snac/_configs/_ssh_config.py

verify sshd ClientAlive configuration
[AB#2864668](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2864668)
I ran `nilrt-snac verify`.

nilrt-snac verify: verify sshd ClientAlive configuration

---

nilrt_snac/_configs/_wireguard_config.py

remove stale opkg configuration logic
The logic is a relic of when we were installing wireguard-tools from the debian package. See #36.
[AB#2921768](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2921768)
The logic causes `verify` to fail.
I ran `nilrt-snac verify`.

wireguard_config: remove stale opkg configuration logic

---

tests/system/wireguard_fixture/__init__.py
tests/system/wireguard_fixture/__main__.py
tests/system/wireguard_fixture/wireguard.py

The wireguard_fixture test module sets up or tears down a wireguard tunnel between a windows LV host and a NILRT client. The script should be run from windows. It uses SSH (via the 'fabric' module) to instrument NILRT-side configuration.
* Add a `tests/system/wireguard_fixture` module that exposes a CLI interface and backing functionality for interacting with wireguard and network interfaces.
* Call `-m wireguard_fixture setup $hostname` to setup a Windows-side tunnel and connect it to the NILRT-side `wglv0` interface.
* Call `-m wireguard_fixture teardown $hostname` to deconfigure the local and remote tunnel.
This script is helpful to setup and tear down test environments for labview, to validate that network communication can continue via the wireguard tunnel. …

tests/system: add wireguard test fixture

---

nilrt_snac/_configs/__init__.py
nilrt_snac/_configs/_sysapi_config.py

install the `ni-sysapi-sshcli` package during `nilrt-snac configure`
System API requires this package in order to communicate from a host to a target over ssh.
[AB#2927009](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2927009)
I ran `nilrt-snac configure` and `nilrt-snac verify`.

nilrt-snac: install ni-sysapi-sshcli

---

docs/CHANGELOG.md
nilrt_snac/_configs/_x11_config.py

Remove the packagegroup-ni-graphical package before removing packagegroup-ni-xfce.
When trying to remove packagegroup-ni-xfce, nilrt-snac configure fails with the following error:
```
* Solver encountered 1 problem(s):
* Problem 1/1:
*   - package packagegroup-ni-graphical-1.0-r0.174.x64 requires packagegroup-ni-xfce, but none of the providers can be installed
*   - conflicting requests
*   - problem with installed package packagegroup-ni-graphical-1.0-r0.174.x64
*
* Solution 1:
*   - allow deinstallation of packagegroup-ni-graphical-1.0-r0.174.x64
* Solution 2:
*   - do not ask to deinstall packagegroup-ni-xfce
*   - do not ask to deinstall packagegroup-ni-xfce
```
On a nilrt VM,
- Ran `nilrt-snac configure --yes`
- Rebooted target
- Ran `nilrt-snac verify`
All operations completed …

Update _x11_config.py to remove packagegroup-ni-graphical

---

azure-pipeline.yaml

Add a Azure Pipeline definition file that prints information about the PR, but does not do any actual testing
MTO has requested the pipeline be securely configured prior to creating the required test VM. This will allow configuring the pipeline to run when there is a PR with the appropriate safeguards for security before any actual testing is ready to run.
* Test runs of this file in the pipeline via manual triggers: https://dev.azure.com/ni/DevCentral/_build/results?buildId=11533082&view=results

Add placeholder Azure Pipeline definition

---

nilrt_snac/_configs/_config_file.py

reduce the default file permissions of created files
These files don't need execute permission.
I ran `nilrt-snac config`.

nilrt-snac config: do not give execute permission to created files

---

README.md
nilrt_snac/__main__.py

Remove the notices from the README and __main__.py
[AB#2944020](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2944020)
The README and `nilrt-snac configure` workflow warn the user that this tool is in-development. That is no longer true.
* None. No time and these should be very safe changes.

Remove development notices

---

docs/CHANGELOG.md
nilrt_snac/_configs/_firewall_config.py

Install ni-firewall-servicedefs to expose NI services to firewalld; enable services for core NI software functionality.
Allow NTP over the public network.
`nilrt-snac configure` succeeds; firewall configuration verified manually.

_firewall_config.py: add NI services to default firewall configuration

---

Makefile
nilrt_snac/_configs/_firewall_config.py
src/x-niroco-static-port.ini

By default, niroco allocates an ephemeral server port, which cannot be effectively firewalled. We can force it to use a specific port with an INI fragment installed to /usr/share/niroco.d, so that _firewall_config.py can allow incoming traffic to that port.
We choose port 55184 more or less entirely arbitrarily, but placing it firmly in the ephemeral range more or less demands that this cannot be the long-term static port decision.
`nilrt-snac configure` succeeds and makes the require changes to the firewalld config. New config file added under /usr/share/niroco.d.

Pin niroco to port 55184 and open it to incoming VPN traffic

---

azure-pipeline.yaml

This commit updates the azure-pipeline.yaml file
to call the mobilize plan that is defined in rtos_oetest.
[AB#2903031](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2903031)
* [Pipeline run](https://dev.azure.com/ni/DevCentral/_build/results?buildId=11799246&view=logs&j=99c8e54b-67b9-5834-54a1-a3c2d9b921c3&t=99c8e54b-67b9-5834-54a1-a3c2d9b921c3)
* [Mobilize run](https://dashboard.ni.systems/dashboard/#/mobilize?plans=b0e2d532b89a11efb54e010101010000:b0e2d533b89a11efb3e6010101010000)

Update azure-pipeline.yaml to call mobilize plan

---

nilrt_snac/_configs/_opkg_config.py

fix opkg .conf file permissions
Standard users need to be able to perform read-only opkg operations.
[AB#2976019](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2976019)
I wrote an automated test for this use case.

nilrt-snac: fix opkg .conf file permissions

---

docs/CHANGELOG.md
nilrt_snac/_common.py
nilrt_snac/_configs/__init__.py
nilrt_snac/_configs/_auditd_config.py
nilrt_snac/_configs/_syslog_ng_config.py

- Add syslog-ng as a dependency
- Create a test event that verifies events are logging to /var/log
800-171 Sections Pertaining to auditing and logging:
https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_171_3_0_0/home?element=SR-03.03.01
https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_171_3_0_0/home?element=SR-03.03.02
https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_171_3_0_0/home?element=SR-03.03.03
https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_171_3_0_0/home?element=SR-03.03.04
https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_171_3_0_0/home?element=SR-03.03.05
https://csrc.nist.gov/projects/cprt/catalog#/cprt/framework/version/SP_800_171_3_0_0/home?element= …

[SNAC Audit] Install and configure syslog-ng from SNAC tool

---

nilrt_snac/_configs/_auditd_config.py
nilrt_snac/_configs/_syslog_ng_config.py

- Added permissions script to init.d in order to ensure permissions are set on symlink path
- Moved initialization of audit conf file to ensure file exists
- Added proper permissions for syslog-ng
- Cleaned up unnecessary indentions in script files
[Bug 3033025](https://dev.azure.com/ni/DevCentral/_workitems/edit/3033025): nilrt-snac verify fails with error code 129. The verification steps that are failing after reboot:
```
Stderr:
E           ( 2938) ERROR nilrt_snac.verify: MISSING: expected action_mail_acct value
E           ( 2939) ERROR nilrt_snac.verify: ERROR: /var/volatile/log is not owned by the 'adm' group.
E           ( 2939) ERROR nilrt_snac.verify: ERROR: /var/volatile/log does not have 770 permissions.
E           ( 2939) ERROR nilrt_snac.main: SNAC mode is not configured …
```

Ensure proper auditd/logging permissions following reboot

---

docs/CHANGELOG.md
nilrt_snac/_configs/_config_file.py
nilrt_snac/_configs/_ntp_config.py
nilrt_snac/_configs/_opkg_config.py
nilrt_snac/_configs/_ssh_config.py
nilrt_snac/_configs/_sudo_config.py
nilrt_snac/_configs/_tmux_config.py
nilrt_snac/_configs/_wifi_config.py

- Added a contains_exact function to address uncaught errors in verification caused by only checking for substrings in the original contains function.
- Reviewed and updated all instances of the contains function in the nilrt-snac package to ensure proper usage.
As stated in the [bug](https://dev.azure.com/ni/DevCentral/_boards/board/t/PRnD%20Security/Work%20Items?System.AssignedTo=eli.engelhardt%40emerson.com&workitem=2995040), the 'contains' function in` _config_file.py` only checks for substring which would allow for improper verification. For example, the nilrt-snac configuration puts in the following entry: **ClientAliveCountMax 4**
However if the user changes it, `nilrt-snac verify` wouldn't throw an error for something like this: **ClientAliveCountMax 40**, which is not the …

Fix verification errors caused by 'contains' function

---

nilrt_snac/_configs/_firewall_config.py

add syslog service to work-out firewalld policy
Users performing remote logging might use this service.
[AB#2870419](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2870419)

_firewall_config.py: add syslog service to work-out policy

---

nilrt_snac/_common.py
nilrt_snac/_configs/_auditd_config.py

avoid FileNotFoundError exception when running `verify` before `configure`
If `/etc/audit/auditd.conf` doesn't exist, then `verify` will print a stack trace and return error 1 rather than `EX_CHECK_FAILURE`.
[AB#3067833](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/3067833)
I ran `nilrt-snac verify`.

_auditd_config.py: do not check permissions on file that doesn't exist

---

docs/CHANGELOG.md
nilrt_snac/_configs/_firewall_config.py

Add ni-logos-xt service to work-out firewalld policy.
Our current policy only allows _incoming_ LogosXT-based traffic, i.e. the traffic for features such as Shared Variables and Network Streams. This allows a remote host to access, e.g., an RT target-hosted Shared Variable. However, a remotely hosted Shared Variable is not accessible to a SNAC-enabled RT target. Allowing _outgoing_ traffic on these ports fixes this.
See [AB3122615](https://dev.azure.com/ni/DevCentral/_workitems/edit/3122615/) for more details.
- Ran `make install` and `make installcheck` against this change.
- Got the failing Shared Variable test to pass by manually adding the following entries to the firewall:
- `firewall-cmd --policy=work-out --add-port=2343/tcp`
- `firewall-cmd --policy=work-out --add-port=59111/tcp`
- …

_firewall_config.py: add ni-logos-xt service to work-out policy

---

docs/CHANGELOG.md
nilrt_snac/_configs/__init__.py
nilrt_snac/_configs/_config_file.py
nilrt_snac/_configs/_usbguard_config.py

* Enable `usbguard_config`
* Remove configuration since it must be installed and configured manually
* Implement verification
* Only verify when usbguard is installed
* Verify /etc/usbguard/rules.conf exists and is not empty
* Change `EqualsDelimitedConfigFile.get()` to handle comments
*  This allows use for USBGuard
[AB#3094079](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/3094079)
* Ran with and without usbguard installed
* Verified missing, empty and non-empty rules.conf files returned expected results

Add USBGuard configuration support, remove configuration support and add verification

---

docs/CHANGELOG.md
nilrt_snac/__init__.py

* Update CHANGELOG.
* Update module version.
LabVIEW 2025Q4 release.

SNAC v3.0.0 Release
